/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloComandas;

import BO.ComandaBO;
import DTOEntrada.CrearComandaDTO;
import DTOSalida.ComandaDTO;
import DTOSalida.ProductoDTO;
import Enums.Estado;
import Enums.ProductoActivo;
import Enums.Tipo;
import GUI.Aplicacion;
import exception.NegocioException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian Moreno
 */
public class PantallaComanda extends javax.swing.JPanel {

    /**
     * Creates new form PantalalaComanda
     */
    Aplicacion app;

    public PantallaComanda(Aplicacion app) {
        this.app = app;
        initComponents();
        mostrarFecha();
        obtenerMesa();

        tablaProductosComanda.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = tablaProductosComanda.rowAtPoint(e.getPoint());
                int columna = tablaProductosComanda.columnAtPoint(e.getPoint());

                // comentarios al dar click en la columna 3 q es la de comentarios
                if (columna == 3) {
                    String respuesta = JOptionPane.showInputDialog(
                            null,
                            "Ingresar comentario"
                    );

                    if (respuesta != null) {
                        //Aqui es donde tienes que sacar el comentario insertado en el inputDialog y meterselo al producto
                        // productosComanda.get(fila).setComentario(respuesta); algo asi masomenos(es un ejemplo de como se podria ver nomas)
                        
                    }
                } else {
                    // cualquier otra columna es para eliminar producto
                    String nombre = (String) tablaProductosComanda.getValueAt(fila, 0);
                    String categoria = (String) tablaProductosComanda.getValueAt(fila, 1);
                    String precio = tablaProductosComanda.getValueAt(fila, 2).toString();

                    int mensajeEliminar = JOptionPane.showConfirmDialog(
                            null,
                            nombre + " - " + categoria + " - " + precio,
                            "¿Desea eliminar este producto?",
                            JOptionPane.YES_NO_OPTION
                    );

                    if (mensajeEliminar == JOptionPane.YES_OPTION) {
                        //simulacion de eliminar un producto nomas lo quito de la tabla xd
                        DefaultTableModel modelo = (DefaultTableModel) tablaProductosComanda.getModel();
                        modelo.removeRow(fila);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlBtnGuardarCliente1 = new GUI.PanelRound();
        btnBuscarCliente = new javax.swing.JLabel();
        pnlBtnGuardarCliente2 = new GUI.PanelRound();
        btnBuscarCliente2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        icnTiempo = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        pnlBtnInsertarMesas3 = new GUI.PanelRound();
        btnInsertarMesas3 = new javax.swing.JLabel();
        pnlBtnInsertarMesas1 = new GUI.PanelRound();
        btnComandaCancelada = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarProducto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarCliente3 = new javax.swing.JLabel();
        pnlBtnInsertarMesas = new GUI.PanelRound();
        btnGuardarComanda = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        lblPropina = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductosComanda = new javax.swing.JTable();
        btnBuscarCliente1 = new javax.swing.JLabel();
        pnlBtnInsertarMesas2 = new GUI.PanelRound();
        btnComandaEntregada = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 202, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Playfair Display", 1, 100)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Comanda");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Mesa : ");
        pnlHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 200, -1));

        pnlBtnGuardarCliente1.setBackground(new java.awt.Color(216, 202, 179));
        pnlBtnGuardarCliente1.setRoundBottomLeft(30);
        pnlBtnGuardarCliente1.setRoundBottomRight(30);
        pnlBtnGuardarCliente1.setRoundTopLeft(30);
        pnlBtnGuardarCliente1.setRoundTopRight(30);
        pnlBtnGuardarCliente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCliente.setBackground(new java.awt.Color(204, 102, 0));
        btnBuscarCliente.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente.setText("CLIENTE: SIN ESPECIFICAR");
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        btnBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarClienteMouseClicked(evt);
            }
        });
        pnlBtnGuardarCliente1.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 50));

        pnlHeader.add(pnlBtnGuardarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 410, -1));

        pnlBtnGuardarCliente2.setBackground(new java.awt.Color(216, 202, 179));
        pnlBtnGuardarCliente2.setRoundBottomLeft(30);
        pnlBtnGuardarCliente2.setRoundBottomRight(30);
        pnlBtnGuardarCliente2.setRoundTopLeft(30);
        pnlBtnGuardarCliente2.setRoundTopRight(30);
        pnlBtnGuardarCliente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCliente2.setBackground(new java.awt.Color(216, 202, 179));
        btnBuscarCliente2.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnBuscarCliente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente2.setText("ESTADO : ABIERTA");
        btnBuscarCliente2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        btnBuscarCliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliente2MouseClicked(evt);
            }
        });
        pnlBtnGuardarCliente2.add(btnBuscarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        pnlHeader.add(pnlBtnGuardarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaAtras.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        pnlHeader.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        icnTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiempo.png"))); // NOI18N
        pnlHeader.add(icnTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, -1));

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        pnlHeader.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 180, 40));

        pnlBtnInsertarMesas3.setBackground(new java.awt.Color(150, 147, 133));
        pnlBtnInsertarMesas3.setRoundBottomLeft(30);
        pnlBtnInsertarMesas3.setRoundBottomRight(30);
        pnlBtnInsertarMesas3.setRoundTopLeft(30);
        pnlBtnInsertarMesas3.setRoundTopRight(30);
        pnlBtnInsertarMesas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnInsertarMesas3MouseClicked(evt);
            }
        });
        pnlBtnInsertarMesas3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsertarMesas3.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnInsertarMesas3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInsertarMesas3.setText("ASINAR CLIENTE");
        btnInsertarMesas3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertarMesas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMesas3MouseClicked(evt);
            }
        });
        pnlBtnInsertarMesas3.add(btnInsertarMesas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 50));

        pnlHeader.add(pnlBtnInsertarMesas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 280, 50));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 180));

        pnlBtnInsertarMesas1.setBackground(new java.awt.Color(214, 14, 14));
        pnlBtnInsertarMesas1.setRoundBottomLeft(30);
        pnlBtnInsertarMesas1.setRoundBottomRight(30);
        pnlBtnInsertarMesas1.setRoundTopLeft(30);
        pnlBtnInsertarMesas1.setRoundTopRight(30);
        pnlBtnInsertarMesas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComandaCancelada.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        btnComandaCancelada.setForeground(new java.awt.Color(255, 255, 255));
        btnComandaCancelada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnComandaCancelada.setText("CANCELADA");
        btnComandaCancelada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComandaCancelada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComandaCanceladaMouseClicked(evt);
            }
        });
        pnlBtnInsertarMesas1.add(btnComandaCancelada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        add(pnlBtnInsertarMesas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 250, 50));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1150, 4));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image (1).png"))); // NOI18N
        btnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseClicked(evt);
            }
        });
        jPanel1.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deshacer (2).png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setText("IMAGEN COMIDAD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel2)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 260, 250));

        btnBuscarCliente3.setBackground(new java.awt.Color(204, 102, 0));
        btnBuscarCliente3.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnBuscarCliente3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscarCliente3.setText("Vista Previa :");
        btnBuscarCliente3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliente3MouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 180, 20));

        pnlBtnInsertarMesas.setBackground(new java.awt.Color(150, 147, 133));
        pnlBtnInsertarMesas.setRoundBottomLeft(30);
        pnlBtnInsertarMesas.setRoundBottomRight(30);
        pnlBtnInsertarMesas.setRoundTopLeft(30);
        pnlBtnInsertarMesas.setRoundTopRight(30);
        pnlBtnInsertarMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnInsertarMesasMouseClicked(evt);
            }
        });
        pnlBtnInsertarMesas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarComanda.setFont(new java.awt.Font("Product Sans Infanity", 0, 24)); // NOI18N
        btnGuardarComanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarComanda.setText("GUARDAR COMANDA");
        btnGuardarComanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarComandaMouseClicked(evt);
            }
        });
        pnlBtnInsertarMesas.add(btnGuardarComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 50));

        jPanel1.add(pnlBtnInsertarMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 260, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 330, 520));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPropina.setBackground(new java.awt.Color(204, 102, 0));
        lblPropina.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        lblPropina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPropina.setText("Propina Sugerida(15%):");
        lblPropina.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblPropina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPropinaMouseClicked(evt);
            }
        });
        panelRound1.add(lblPropina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 370, 30));

        lblSubtotal.setBackground(new java.awt.Color(204, 102, 0));
        lblSubtotal.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubtotal.setText("Subtotal:");
        lblSubtotal.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblSubtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSubtotalMouseClicked(evt);
            }
        });
        panelRound1.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 30));

        lblTotal.setBackground(new java.awt.Color(204, 102, 0));
        lblTotal.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("Total:");
        lblTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTotalMouseClicked(evt);
            }
        });
        panelRound1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, 20));

        lblIVA.setBackground(new java.awt.Color(204, 102, 0));
        lblIVA.setFont(new java.awt.Font("Product Sans Infanity", 1, 18)); // NOI18N
        lblIVA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIVA.setText("IVA:");
        lblIVA.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblIVA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIVAMouseClicked(evt);
            }
        });
        panelRound1.add(lblIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 370, 30));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 520, 140));

        tablaProductosComanda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tablaProductosComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoria", "Precio", "Comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductosComanda.setRowHeight(30);
        tablaProductosComanda.getTableHeader().setResizingAllowed(false);
        tablaProductosComanda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaProductosComanda);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 780, 310));

        btnBuscarCliente1.setBackground(new java.awt.Color(204, 102, 0));
        btnBuscarCliente1.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnBuscarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscarCliente1.setText("MARCAR COMO :");
        btnBuscarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliente1MouseClicked(evt);
            }
        });
        add(btnBuscarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, 30));

        pnlBtnInsertarMesas2.setBackground(new java.awt.Color(51, 204, 0));
        pnlBtnInsertarMesas2.setRoundBottomLeft(30);
        pnlBtnInsertarMesas2.setRoundBottomRight(30);
        pnlBtnInsertarMesas2.setRoundTopLeft(30);
        pnlBtnInsertarMesas2.setRoundTopRight(30);
        pnlBtnInsertarMesas2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComandaEntregada.setFont(new java.awt.Font("Product Sans Infanity", 0, 18)); // NOI18N
        btnComandaEntregada.setForeground(new java.awt.Color(255, 255, 255));
        btnComandaEntregada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnComandaEntregada.setText("ENTREGADA");
        btnComandaEntregada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComandaEntregada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComandaEntregadaMouseClicked(evt);
            }
        });
        pnlBtnInsertarMesas2.add(btnComandaEntregada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        add(pnlBtnInsertarMesas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 250, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarComandaMouseClicked
        //Ocupa la validacion para saber si la comanda ya existe
        guardarComanda();
    }//GEN-LAST:event_btnGuardarComandaMouseClicked

    private void btnBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarClienteMouseClicked

    }//GEN-LAST:event_btnBuscarClienteMouseClicked

    private void btnBuscarCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCliente1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        app.mostrarMenuPrincipal();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnBuscarCliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliente2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCliente2MouseClicked

    private void pnlBtnInsertarMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnInsertarMesasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBtnInsertarMesasMouseClicked

    private void lblPropinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPropinaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPropinaMouseClicked

    private void lblSubtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubtotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSubtotalMouseClicked

    private void lblTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalMouseClicked

    private void lblIVAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIVAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIVAMouseClicked

    private void btnBuscarCliente3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliente3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCliente3MouseClicked

    private void btnComandaCanceladaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComandaCanceladaMouseClicked
        String mensaje = "<html>"
                + "<b>¿Desea cancelar la comanda?</b><br>"
                + "Una vez eliminada la comanda no se podrán revertir los cambios"
                + "</html>";
        int mensajeCancelarComanda = JOptionPane.showConfirmDialog(
                null,
                mensaje,
                " ",
                JOptionPane.YES_NO_OPTION
        );
    }//GEN-LAST:event_btnComandaCanceladaMouseClicked

    private void btnComandaEntregadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComandaEntregadaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComandaEntregadaMouseClicked

    private void btnInsertarMesas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMesas3MouseClicked
        app.setSiguienteComanda(true);
        app.mostrarPantallaConsultarCliente();
    }//GEN-LAST:event_btnInsertarMesas3MouseClicked

    private void pnlBtnInsertarMesas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnInsertarMesas3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBtnInsertarMesas3MouseClicked

    private void btnAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseClicked
        // TODO add your handling code here:
        registrarProducto();
    }//GEN-LAST:event_btnAgregarProductoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregarProducto;
    private javax.swing.JLabel btnBuscarCliente;
    private javax.swing.JLabel btnBuscarCliente1;
    private javax.swing.JLabel btnBuscarCliente2;
    private javax.swing.JLabel btnBuscarCliente3;
    private javax.swing.JLabel btnComandaCancelada;
    private javax.swing.JLabel btnComandaEntregada;
    private javax.swing.JLabel btnGuardarComanda;
    private javax.swing.JLabel btnInsertarMesas3;
    private javax.swing.JLabel icnTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblPropina;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private GUI.PanelRound panelRound1;
    private GUI.PanelRound pnlBtnGuardarCliente1;
    private GUI.PanelRound pnlBtnGuardarCliente2;
    private GUI.PanelRound pnlBtnInsertarMesas;
    private GUI.PanelRound pnlBtnInsertarMesas1;
    private GUI.PanelRound pnlBtnInsertarMesas2;
    private GUI.PanelRound pnlBtnInsertarMesas3;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tablaProductosComanda;
    // End of variables declaration//GEN-END:variables

    //metodos auxiliares
    public void obtenerMesa() {
        jLabel1.setText("MESA " + app.getMesa());
    }

    private void mostrarFecha() {
        Timer timer = new Timer(1000, e -> {
            LocalTime horaActual = LocalTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm a");
            lblHora.setText(horaActual.format(formatter));
        });
        timer.start();
    }

    public void cargarCliente() {
        String cliente = app.getClienteSeleccionado();
        if (cliente == null) {
            btnBuscarCliente.setText("CLIENTE : SIN ESPECIFICAR");
        } else {
            // Eliminar el prefijo y obtener solo el nombre completo
            String nombreCompleto = cliente.replace("Cliente :", "").trim();
            String[] partes = nombreCompleto.split("\\s+");

            String nombre = partes[0];
            String apellidoPaterno = (partes.length > 1) ? partes[1] : "";
            String inicialApellidoMaterno = (partes.length > 2) ? " " + partes[2].charAt(0) + "." : "";

            btnBuscarCliente.setText("CLIENTE : " + nombre + " " + apellidoPaterno + inicialApellidoMaterno);
            btnBuscarCliente.repaint();

        }
    }

    public void registrarProducto() {
        String nombreProducto1 = "Pasta Linguini";
        double precioProducto1 = 250.00;
        Tipo tipoSeleccionado1 = Tipo.PLATILLO;//quitar imports de enums
        ProductoActivo productoActivo1 = ProductoActivo.Habilitado;
        ProductoDTO producto1 = new ProductoDTO(nombreProducto1, precioProducto1, tipoSeleccionado1, productoActivo1);

        String nombreProducto2 = "Pizza Margarita";
        double precioProducto2 = 180.00;
        Tipo tipoSeleccionado2 = Tipo.PLATILLO;
        ProductoActivo productoActivo2 = ProductoActivo.Habilitado;

        ProductoDTO producto2 = new ProductoDTO(nombreProducto2, precioProducto2, tipoSeleccionado2, productoActivo2);

        DefaultTableModel modeloTabla = (DefaultTableModel) tablaProductosComanda.getModel();

        modeloTabla.addRow(new Object[]{
            producto1.getNombre(),
            producto1.getTipo().toString(),
            producto1.getPrecio(),
            "Introducir"
        });

        modeloTabla.addRow(new Object[]{
            producto2.getNombre(),
            producto2.getTipo().toString(),
            producto2.getPrecio(),
            "Introducir"
        });

        calcularTotal();
    }

    public void calcularTotal() {
        double total = 0.0;

        // Recorre todas las filas de la tabla
        for (int i = 0; i < tablaProductosComanda.getRowCount(); i++) {
            String precioStr = tablaProductosComanda.getValueAt(i, 2).toString();

            // Convierte el string a double (con manejo de errores)
            try {
                double precio = Double.parseDouble(precioStr);
                total += precio;
            } catch (NumberFormatException e) {
                System.err.println("Error al convertir el precio en la fila " + i + ": " + precioStr);
            }
        }

        // Calcula subtotal, IVA y propina sobre el total acumulado
        double subtotal = total / 1.16;
        double iva = total - subtotal;
        double propina = total * 1.15;

        // Muestra los resultados
        lblSubtotal.setText("Subtotal: $" + String.format("%.2f", subtotal));
        lblIVA.setText("IVA: $" + String.format("%.2f", iva));
        lblTotal.setText("Total: $" + String.format("%.2f", total));
        lblPropina.setText("Propina: $" + String.format("%.2f", propina));
    }
    
    public void guardarComanda(){
        CrearComandaDTO comandaDTO = new CrearComandaDTO();
      
        comandaDTO.setEstado(Estado.Abierta);
        comandaDTO.setFechaHora(LocalDateTime.now());
        comandaDTO.setNumeroMesa(Integer.parseInt(app.getMesa()));
        try{
            app.guardarComanda(comandaDTO);    
        }catch(NegocioException ex){
            ex.printStackTrace();
        }
        
    }

}
