/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloComandas;

import GUI.Aplicacion;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

/**
 *
 * @author Sebastian Moreno
 */
public class PantallaComanda extends javax.swing.JPanel {

    /**
     * Creates new form PantalalaComanda
     */
    Aplicacion app;

    public PantallaComanda(Aplicacion app) {
        this.app = app;
        initComponents();
        mostrarFecha();
        obtenerMesa();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlBtnInsertarMesas = new GUI.PanelRound();
        btnInsertarMesas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlBtnGuardarCliente1 = new GUI.PanelRound();
        btnBuscarCliente = new javax.swing.JLabel();
        pnlBtnGuardarCliente2 = new GUI.PanelRound();
        btnBuscarCliente2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        icnTiempo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReporteClientes = new javax.swing.JTable();
        btnBuscarCliente1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 202, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Playfair Display", 1, 100)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Comanda");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pnlBtnInsertarMesas.setBackground(new java.awt.Color(51, 204, 0));
        pnlBtnInsertarMesas.setRoundBottomLeft(30);
        pnlBtnInsertarMesas.setRoundBottomRight(30);
        pnlBtnInsertarMesas.setRoundTopLeft(30);
        pnlBtnInsertarMesas.setRoundTopRight(30);
        pnlBtnInsertarMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnInsertarMesasMouseClicked(evt);
            }
        });
        pnlBtnInsertarMesas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsertarMesas.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        btnInsertarMesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInsertarMesas.setText("ASINAR CLIENTE");
        btnInsertarMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertarMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMesasMouseClicked(evt);
            }
        });
        pnlBtnInsertarMesas.add(btnInsertarMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 60));

        pnlHeader.add(pnlBtnInsertarMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 260, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Mesa : ");
        pnlHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 200, -1));

        pnlBtnGuardarCliente1.setBackground(new java.awt.Color(204, 102, 0));
        pnlBtnGuardarCliente1.setRoundBottomLeft(30);
        pnlBtnGuardarCliente1.setRoundBottomRight(30);
        pnlBtnGuardarCliente1.setRoundTopLeft(30);
        pnlBtnGuardarCliente1.setRoundTopRight(30);
        pnlBtnGuardarCliente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCliente.setBackground(new java.awt.Color(204, 102, 0));
        btnBuscarCliente.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente.setText("CLIENTE: SIN ESPECIFICAR");
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        btnBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarClienteMouseClicked(evt);
            }
        });
        pnlBtnGuardarCliente1.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 50));

        pnlHeader.add(pnlBtnGuardarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 410, -1));

        pnlBtnGuardarCliente2.setBackground(new java.awt.Color(204, 102, 0));
        pnlBtnGuardarCliente2.setRoundBottomLeft(30);
        pnlBtnGuardarCliente2.setRoundBottomRight(30);
        pnlBtnGuardarCliente2.setRoundTopLeft(30);
        pnlBtnGuardarCliente2.setRoundTopRight(30);
        pnlBtnGuardarCliente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCliente2.setBackground(new java.awt.Color(204, 102, 0));
        btnBuscarCliente2.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnBuscarCliente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente2.setText("ESTADO : ABIERTA");
        btnBuscarCliente2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        btnBuscarCliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliente2MouseClicked(evt);
            }
        });
        pnlBtnGuardarCliente2.add(btnBuscarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        pnlHeader.add(pnlBtnGuardarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaAtras.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        pnlHeader.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 180));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1150, 4));

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, 180, 40));

        icnTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiempo.png"))); // NOI18N
        add(icnTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("IMAGEN COMIDAD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 158, -1, -1));

        jLabel3.setText("BOTON AGREGAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel5.setText("BTNReiniciar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 330, 520));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 480, 140));

        tablaReporteClientes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tablaReporteClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoria", "Precio", "Comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaReporteClientes.setRowHeight(30);
        jScrollPane1.setViewportView(tablaReporteClientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 740, 310));

        btnBuscarCliente1.setBackground(new java.awt.Color(204, 102, 0));
        btnBuscarCliente1.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnBuscarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente1.setText("MARCAR COMO :");
        btnBuscarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliente1MouseClicked(evt);
            }
        });
        add(btnBuscarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 280, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMesasMouseClicked
        app.mostrarPantallaRegistrarCliente();
    }//GEN-LAST:event_btnInsertarMesasMouseClicked

    private void btnBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarClienteMouseClicked

    }//GEN-LAST:event_btnBuscarClienteMouseClicked

    private void btnBuscarCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCliente1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        app.mostrarMenuPrincipal();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnBuscarCliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliente2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCliente2MouseClicked

    private void pnlBtnInsertarMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnInsertarMesasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBtnInsertarMesasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarCliente;
    private javax.swing.JLabel btnBuscarCliente1;
    private javax.swing.JLabel btnBuscarCliente2;
    private javax.swing.JLabel btnInsertarMesas;
    private javax.swing.JLabel icnTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHora;
    private GUI.PanelRound panelRound1;
    private GUI.PanelRound pnlBtnGuardarCliente1;
    private GUI.PanelRound pnlBtnGuardarCliente2;
    private GUI.PanelRound pnlBtnInsertarMesas;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tablaReporteClientes;
    // End of variables declaration//GEN-END:variables

    //metodos auxiliares
    public void obtenerMesa() {
        jLabel1.setText("MESA " + app.getMesa());
    }

    private void mostrarFecha() {
        Timer timer = new Timer(1000, e -> {
            LocalTime horaActual = LocalTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm a");
            lblHora.setText(horaActual.format(formatter));
        });
        timer.start();
    }
}
