package GUI.ModuloIngredientes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import DTOEntrada.CrearIngredienteDTO;
import Enums.UnidadMedida;
import GUI.*;
import GUI.Aplicacion;
import exception.NegocioException;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.Time;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Sebastian Moreno
 */
public class FormularioRegistrarIngrediente extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipalRestaurante
     */
    Aplicacion app;

    public FormularioRegistrarIngrediente(Aplicacion app) {
        this.app = app;
        initComponents();
        cbxUnidades.setUI(null);
        cbxUnidades.setUI(new javax.swing.plaf.basic.BasicComboBoxUI());
        cbxUnidades.setBackground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableIngredientes = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        inputStockInicial = new javax.swing.JTextField();
        panelRound2 = new GUI.PanelRound();
        inputNombre = new javax.swing.JTextField();
        panelRound3 = new GUI.PanelRound();
        cbxUnidades = new javax.swing.JComboBox<>();
        panelRound6 = new GUI.PanelRound();
        btnRegistrarIngrediente = new javax.swing.JLabel();
        panelRound4 = new GUI.PanelRound();
        btnCancelar = new javax.swing.JLabel();
        panelRound5 = new GUI.PanelRound();
        bntModificarIngrediente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 202, 179));
        setForeground(new java.awt.Color(216, 202, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 100)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Registrar Ingrediente");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 180));

        jSeparator3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1150, 10));

        tableIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Ingrediente", "Unidad de medida", "Stock"
            }
        ));
        jScrollPane2.setViewportView(tableIngredientes);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 250, 570, 340));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Stock inicial:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Inventario de ingredientes");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 210, 290, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Unidad de medida:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);

        inputStockInicial.setBorder(null);
        inputStockInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputStockInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStockInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 250, 50));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);

        inputNombre.setBorder(null);
        inputNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 250, 50));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxUnidades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRAMOS", "PIEZAS", "MILILITROS" }));
        cbxUnidades.setBorder(null);
        cbxUnidades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbxUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUnidadesActionPerformed(evt);
            }
        });
        panelRound3.add(cbxUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 50));

        add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 250, 50));

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setRoundBottomLeft(30);
        panelRound6.setRoundBottomRight(30);
        panelRound6.setRoundTopLeft(30);
        panelRound6.setRoundTopRight(30);

        btnRegistrarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistrarIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrarIngrediente.setText("Registrar Ingrediente");
        btnRegistrarIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarIngredienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 320, 50));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(30);
        panelRound4.setRoundBottomRight(30);
        panelRound4.setRoundTopLeft(30);
        panelRound4.setRoundTopRight(30);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 320, 50));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(30);
        panelRound5.setRoundBottomRight(30);
        panelRound5.setRoundTopLeft(30);
        panelRound5.setRoundTopRight(30);

        bntModificarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bntModificarIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntModificarIngrediente.setText("Modificar Ingrediente");
        bntModificarIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntModificarIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntModificarIngredienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bntModificarIngrediente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bntModificarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 320, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Nombre:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbxUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUnidadesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxUnidadesActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputStockInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStockInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStockInicialActionPerformed

    private void btnRegistrarIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarIngredienteMouseClicked
        // TODO add your handling code here:
        registrarIngrediente();
    }//GEN-LAST:event_btnRegistrarIngredienteMouseClicked

    private void bntModificarIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntModificarIngredienteMouseClicked
        // TODO add your handling code here:
        
        String nuevoStockStr = JOptionPane.showInputDialog(this, "Ingrese el nuevo stock para " + "asd" + ":", "Modificar Stock", JOptionPane.PLAIN_MESSAGE);
        Integer nuevoStock = Integer.parseInt(nuevoStockStr.trim());
        
    }//GEN-LAST:event_bntModificarIngredienteMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        app.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bntModificarIngrediente;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnRegistrarIngrediente;
    private javax.swing.JComboBox<String> cbxUnidades;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputStockInicial;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private GUI.PanelRound panelRound1;
    private GUI.PanelRound panelRound2;
    private GUI.PanelRound panelRound3;
    private GUI.PanelRound panelRound4;
    private GUI.PanelRound panelRound5;
    private GUI.PanelRound panelRound6;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tableIngredientes;
    // End of variables declaration//GEN-END:variables

//
    public void registrarIngrediente() {
        String nombreIngrediente = inputNombre.getText().trim();
        String unidadSeleccionada = (String) cbxUnidades.getSelectedItem();
        UnidadMedida unidadMedida = UnidadMedida.valueOf(unidadSeleccionada); //seleccionamos la opcion dle combobox y la casteamos a UnidadMedida
        Integer stock = Integer.parseInt(inputStockInicial.getText().trim());

        if (nombreIngrediente.isEmpty() || nombreIngrediente.equals("Nombre del ingrediente")) {
            JOptionPane.showMessageDialog(this, "Todos los campos (*) son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String ingredienteEntero = stock + " " + unidadMedida + " " + nombreIngrediente;
        CrearIngredienteDTO ingrediente = new CrearIngredienteDTO(nombreIngrediente, stock, unidadMedida);

        try {
            app.registrarIngrediente(ingrediente);
            JOptionPane.showMessageDialog(this, "Ingrediente registrado exitosamente!\n ",
                    ingredienteEntero, JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar el ingrediente: " + ex.getMessage(),
                    "Error en Registro", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    public void actualizarStock(){
        //String nombreIngrediente = 
        
    }
    
    //Falta cargar datos en tabla y eliminar ingrediente de la tabla con doble click

    //Auxiliares
    public void limpiarCampos() {
        inputNombre.setText("");
        inputStockInicial.setText("");
    }
}
