/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Productos;

import DTOSalida.ProductoDTO;
import Enums.Tipo;
import GUI.Aplicacion;
import exception.NegocioException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.ToolTipManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SDavidLedesma
 */
public class BuscarProducto extends javax.swing.JPanel {

    private Aplicacion app;
    private DefaultTableModel modeloTabla;
    private List<ProductoDTO> productos;  // esta es la lista que vas a usar

    /**
     * Creates new form BuscarProducto
     *
     * @param app
     */
    public BuscarProducto(Aplicacion app) {
        this.app = app;
        initComponents();
        String[] columnas = {"Id", "Producto", "Categoria", "Precio", "Des/Habilitado", "Ingredientes"};
        DefaultTableModel model = new DefaultTableModel(null, columnas);
        tablaProductos.setModel(model);
        tablaProductos.setDefaultEditor(Object.class, null);
        productos = new ArrayList<>();

        cargarMeotdosAuxiliares();
        setearToolTips();

        comboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarProductoPorTipo();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        btnHabilitar = new javax.swing.JButton();

        setBackground(new java.awt.Color(216, 202, 179));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setText("Buscar un Producto");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaAtras.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        lblHora.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(217, 217, 217)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(lblHora)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHora)
                .addGap(32, 32, 32))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Buscar Categoria:");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLATILLO", "BEBIDA", "POSTRE" }));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setText("Nombre:");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Producto", "Categoria", "Precio", "Des/Habilitado", "Ingredientes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.setRowHeight(30);
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        btnCancelar.setText("Cancelar");

        btnEliminarProducto.setText("Deshabilitar Producto");
        btnEliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarProductoMouseClicked(evt);
            }
        });
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja.png"))); // NOI18N

        btnHabilitar.setText("Habilitar Producto");
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabel4)))
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnHabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        app.mostrarRegistroProducto();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        deshabilitarProducto();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
        habilitarProducto();
    }//GEN-LAST:event_btnHabilitarActionPerformed

    private void btnEliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProductoMouseClicked

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        if (app.isSiguienteComanda() && evt.getClickCount() == 2) {
            // Obtener la fila seleccionada
            int filaSeleccionada = tablaProductos.getSelectedRow();

            // Verificar si hay una fila seleccionada
            if (filaSeleccionada != -1) {
                // Obtener el valor de las columnas de la fila seleccionada
                String nombreProducto = (String) tablaProductos.getValueAt(filaSeleccionada, 1); // Columna 1: nombre
                String categoriaStr = tablaProductos.getValueAt(filaSeleccionada, 2).toString(); // Columna 2: categoría como String
                Tipo tipoNuevo = Tipo.valueOf(categoriaStr); // Convertir el String a un Enum de Tipo
                String precioStr = tablaProductos.getValueAt(filaSeleccionada, 3).toString(); // Columna 3: precio como String

                // Convertir el precio a Double en lugar de Integer
                Double precio = Double.parseDouble(precioStr);
                // Crear el ProductoDTO con los valores obtenidos
                ProductoDTO producto = new ProductoDTO();
                producto.setNombre(nombreProducto);
                producto.setTipo(tipoNuevo);
                producto.setPrecio(precio);

                // Establecer el producto temporal
                app.setProductoTemporal(producto);

                // Reconstruir y mostrar la pantalla de comanda
                app.reconstruirPantallaComanda();
                app.mostrarPantallaComanda();
            }
        }
    }//GEN-LAST:event_tablaProductosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JToggleButton btnEliminarProducto;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void agregarDocumentListener(JTextField textField) {
        textField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                realizarBusqueda();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                realizarBusqueda();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                realizarBusqueda();
            }
        });
    }

    private void realizarBusqueda() {
        ProductoDTO productoFiltro = new ProductoDTO();

        String nombre = txtNombre.getText().trim();
        if (!nombre.isEmpty()) {
            productoFiltro.setNombre(nombre);
        }

        //String tipoString = (String) comboBox.getSelectedItem();
        //Tipo tipo = Tipo.valueOf(tipoString);
        //if (!tipoString.isEmpty()) {
        //   productoFiltro.setTipo(tipo);
        //}
        List<ProductoDTO> productosEncontrados = null;
        try {
            productosEncontrados = app.buscarProductos(productoFiltro);
        } catch (NegocioException ex) {
            Logger.getLogger(BuscarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (productosEncontrados == null) {
            actualizarTabla(productosEncontrados);
        } else {

            actualizarTabla(productosEncontrados);
        }
    }

    private void actualizarTabla(List<ProductoDTO> productos) {
        DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
        model.setRowCount(0);

        if (productos == null || productos.isEmpty()) {
            model.addRow(new Object[]{"  NO SE ", " ENCONTRARON ", " DATOS PARA ESTA ", " BUSQUEDA "});
        } else {
            //llenar la tabla
            for (ProductoDTO producto : productos) {
                model.addRow(new Object[]{
                    producto.getId(),
                    producto.getNombre(),
                    producto.getTipo(),
                    producto.getPrecio(),
                    producto.getProductoActivo(),
                    producto.getIngredienteProducto()
                });
            }
        }

        // Ocultar la columna de ID
        int numColumnas = tablaProductos.getColumnCount();
        if (numColumnas
                < 5) {
            tablaProductos.getColumnModel().getColumn(0).setMinWidth(0);
            tablaProductos.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaProductos.getColumnModel().getColumn(0).setWidth(0);
        }
    }

    private void limpiarCampos() {
        txtNombre.setText("");
    }

    private void setearToolTips() {
        txtNombre.setToolTipText("Introcude el nombre del producto");

        ToolTipManager.sharedInstance().setInitialDelay(100);     // Espera 100 ms para aparecer
        ToolTipManager.sharedInstance().setDismissDelay(10000);   // Permanece visible 10 segundos
        ToolTipManager.sharedInstance().setReshowDelay(100);
    }

    public void cargarMeotdosAuxiliares() {
        agregarDocumentListener(txtNombre);

        setearToolTips();
    }

    private void buscarProductoPorTipo() {
        try {
            String categoriaStr = (String) comboBox.getSelectedItem();
            Tipo categoria = Tipo.valueOf(categoriaStr);

            ProductoDTO filtro = new ProductoDTO();
            filtro.setTipo(categoria);

            List<ProductoDTO> productos = app.buscarProductos(filtro);
            actualizarTabla(productos);
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar productos: " + e.getMessage());
        }
    }

    private void deshabilitarProducto() {
        int filaSeleccionada = tablaProductos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(BuscarProducto.this, "Por favor, selecciona un producto de la tabla.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                BuscarProducto.this,
                "¿Estás seguro de que deseas deshabilitar este producto?",
                "Confirmar deshabilitación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                // Obtener el ID desde la columna oculta (columna 5)
                Long idProducto = Long.parseLong(tablaProductos.getValueAt(filaSeleccionada, 0).toString());

                ProductoDTO productoDTO = new ProductoDTO();
                productoDTO.setId(idProducto);

                app.deshabilitarProducto(productoDTO);
                JOptionPane.showMessageDialog(BuscarProducto.this, "Producto deshabilitado exitosamente.");

                // Refrescar la tabla
                realizarBusqueda();

            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(BuscarProducto.this, "Error al deshabilitar producto: " + ex.getMessage());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(BuscarProducto.this, "Error inesperado: " + ex.getMessage());
            }
        }

    }

    private void habilitarProducto() {
        int filaSeleccionada = tablaProductos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(BuscarProducto.this, "Por favor, selecciona un producto de la tabla.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                BuscarProducto.this,
                "¿Estás seguro de que deseas Habilitar este producto?",
                "Confirmar Habilitacion",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                // Obtener el ID desde la columna oculta (columna 5)
                Long idProducto = Long.parseLong(tablaProductos.getValueAt(filaSeleccionada, 0).toString());

                ProductoDTO productoDTO = new ProductoDTO();
                productoDTO.setId(idProducto);

                app.habilitarProducto(productoDTO);
                JOptionPane.showMessageDialog(BuscarProducto.this, "Producto habilitado exitosamente.");

                // Refrescar la tabla
                realizarBusqueda();

            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(BuscarProducto.this, "Error al habilitar producto: " + ex.getMessage());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(BuscarProducto.this, "Error inesperado: " + ex.getMessage());
            }
        }

    }

}
