/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloReportes;

import GUI.Aplicacion;

/**
 *
 * @author Sebastian Moreno
 */
public class MenuReportes extends javax.swing.JPanel {

    /**
     * Creates new form MenuReportes
     */
    Aplicacion app;

    public MenuReportes(Aplicacion app) {
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linea = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        icnAtras = new javax.swing.JLabel();
        pnlBotonComandas = new GUI.PanelRound();
        btnComandas2 = new javax.swing.JLabel();
        btnComandas1 = new javax.swing.JLabel();
        pnlBotonClientes = new GUI.PanelRound();
        btnClientes1 = new javax.swing.JLabel();
        btnClientes2 = new javax.swing.JLabel();
        txtInstrucciones = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 202, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linea.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout lineaLayout = new javax.swing.GroupLayout(linea);
        linea.setLayout(lineaLayout);
        lineaLayout.setHorizontalGroup(
            lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lineaLayout.setVerticalGroup(
            lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1150, 4));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setBackground(new java.awt.Color(0, 0, 0));
        txtTitulo.setFont(new java.awt.Font("Playfair Display", 1, 100)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTitulo.setText("Reportes");
        txtTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeader.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        icnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaAtras.png"))); // NOI18N
        icnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icnAtrasMouseClicked(evt);
            }
        });
        pnlHeader.add(icnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 180));

        pnlBotonComandas.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotonComandas.setRoundBottomLeft(30);
        pnlBotonComandas.setRoundBottomRight(30);
        pnlBotonComandas.setRoundTopLeft(30);
        pnlBotonComandas.setRoundTopRight(30);
        pnlBotonComandas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComandas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comandas.png"))); // NOI18N
        btnComandas2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComandas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComandas2MouseClicked(evt);
            }
        });
        pnlBotonComandas.add(btnComandas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        btnComandas1.setBackground(new java.awt.Color(0, 0, 0));
        btnComandas1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 36)); // NOI18N
        btnComandas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnComandas1.setText("COMANDAS");
        btnComandas1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnComandas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComandas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComandas1MouseClicked(evt);
            }
        });
        pnlBotonComandas.add(btnComandas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 310));

        add(pnlBotonComandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 330, 310));

        pnlBotonClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotonClientes.setRoundBottomLeft(30);
        pnlBotonClientes.setRoundBottomRight(30);
        pnlBotonClientes.setRoundTopLeft(30);
        pnlBotonClientes.setRoundTopRight(30);
        pnlBotonClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil (2).png"))); // NOI18N
        btnClientes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientes1MouseClicked(evt);
            }
        });
        pnlBotonClientes.add(btnClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 200, 210));

        btnClientes2.setBackground(new java.awt.Color(0, 0, 0));
        btnClientes2.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 36)); // NOI18N
        btnClientes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClientes2.setText("CLIENTES");
        btnClientes2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClientes2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientes2MouseClicked(evt);
            }
        });
        pnlBotonClientes.add(btnClientes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 310));

        add(pnlBotonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 330, 310));

        txtInstrucciones.setBackground(new java.awt.Color(0, 0, 0));
        txtInstrucciones.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 36)); // NOI18N
        txtInstrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInstrucciones.setText("Selecciona el modo de reporte :");
        txtInstrucciones.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtInstrucciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(txtInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 630, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void icnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icnAtrasMouseClicked
        app.mostrarMenuPrincipal();
    }//GEN-LAST:event_icnAtrasMouseClicked

    private void btnClientes2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientes2MouseClicked
        app.mostrarPantallaReporteClientes();
    }//GEN-LAST:event_btnClientes2MouseClicked

    private void btnComandas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComandas2MouseClicked
        app.mostrarPantallaReporteComandas();
    }//GEN-LAST:event_btnComandas2MouseClicked

    private void btnComandas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComandas1MouseClicked
        app.mostrarPantallaReporteComandas();
    }//GEN-LAST:event_btnComandas1MouseClicked

    private void btnClientes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientes1MouseClicked
        app.mostrarPantallaReporteClientes();
    }//GEN-LAST:event_btnClientes1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClientes1;
    private javax.swing.JLabel btnClientes2;
    private javax.swing.JLabel btnComandas1;
    private javax.swing.JLabel btnComandas2;
    private javax.swing.JLabel icnAtras;
    private javax.swing.JPanel linea;
    private GUI.PanelRound pnlBotonClientes;
    private GUI.PanelRound pnlBotonComandas;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JLabel txtInstrucciones;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
