/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTOSalida.MesaDTO;
import exception.NegocioException;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.Time;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian Moreno
 */
public class MenuPrincipalRestaurante extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipalRestaurante
     */
    Aplicacion app;

    public MenuPrincipalRestaurante(Aplicacion app) {
        this.app = app;
        initComponents();
        centrarTextoTabla(tablaMesas);
        calcularHora();
        validarMesasExistentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlBtnGuardarCliente3 = new GUI.PanelRound();
        btnBuscarCliente2 = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlBtnInsertarMesas = new GUI.PanelRound();
        btnInsertarMesas = new javax.swing.JLabel();
        pnlHeader1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMesas = new javax.swing.JTable();
        hora = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnlBtnGuardarCliente2 = new GUI.PanelRound();
        btnBuscarCliente1 = new javax.swing.JLabel();
        icnTiempo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 202, 179));
        setForeground(new java.awt.Color(216, 202, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1150, 4));

        pnlBtnGuardarCliente3.setBackground(new java.awt.Color(153, 0, 0));
        pnlBtnGuardarCliente3.setRoundBottomLeft(30);
        pnlBtnGuardarCliente3.setRoundBottomRight(30);
        pnlBtnGuardarCliente3.setRoundTopLeft(30);
        pnlBtnGuardarCliente3.setRoundTopRight(30);
        pnlBtnGuardarCliente3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCliente2.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        btnBuscarCliente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente2.setText("SALIR");
        btnBuscarCliente2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliente2MouseClicked(evt);
            }
        });
        pnlBtnGuardarCliente3.add(btnBuscarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 60));

        add(pnlBtnGuardarCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 62, 182, 60));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Playfair Display", 1, 100)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Restaurante");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 15, -1, -1));

        pnlBtnInsertarMesas.setBackground(new java.awt.Color(51, 204, 0));
        pnlBtnInsertarMesas.setRoundBottomLeft(30);
        pnlBtnInsertarMesas.setRoundBottomRight(30);
        pnlBtnInsertarMesas.setRoundTopLeft(30);
        pnlBtnInsertarMesas.setRoundTopRight(30);
        pnlBtnInsertarMesas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsertarMesas.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        btnInsertarMesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInsertarMesas.setText("INSERTAR MESAS");
        btnInsertarMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertarMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMesasMouseClicked(evt);
            }
        });
        pnlBtnInsertarMesas.add(btnInsertarMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 60));

        pnlHeader.add(pnlBtnInsertarMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 60, 182, 60));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 180));

        pnlHeader1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("REPORTE");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("PRODUCTO");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("GENERAR ");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("REGISTRAR");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("FRECUENTE");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("INGREDIENTE");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("REGISTRAR");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, 40));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("REGISTRAR");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 150, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("CLIENTE");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 140, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlHeader1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 260, 4));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlHeader1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 4));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlHeader1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 260, 4));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil (1).png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 70, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verdura.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 70, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caja.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/documento.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        pnlHeader1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        add(pnlHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 260, 520));

        tablaMesas.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 36)); // NOI18N
        tablaMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMesas.setRowHeight(80);
        jScrollPane1.setViewportView(tablaMesas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 590, 330));

        hora.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        hora.setText("Hora");
        add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(957, 180, 160, 36));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("INICIAR  COMANDA  EN  MESA :");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 590, 380));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel16.setText("Rol : Administrador");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 181, 230, 40));

        pnlBtnGuardarCliente2.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnGuardarCliente2.setRoundBottomLeft(30);
        pnlBtnGuardarCliente2.setRoundBottomRight(30);
        pnlBtnGuardarCliente2.setRoundTopLeft(30);
        pnlBtnGuardarCliente2.setRoundTopRight(30);
        pnlBtnGuardarCliente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCliente1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        btnBuscarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente1.setText("CONSULTAR COMANDAS ACTIVAS");
        btnBuscarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliente1MouseClicked(evt);
            }
        });
        pnlBtnGuardarCliente2.add(btnBuscarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 340, 40));

        add(pnlBtnGuardarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 360, 40));

        icnTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiempo.png"))); // NOI18N
        add(icnTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 178, -1, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario.png"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        app.mostrarMenuReportes();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        app.mostrarPantallaRegistrarCliente();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        app.mostrarPantallaRegistrarCliente();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        app.mostrarPantallaRegistrarCliente();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnInsertarMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMesasMouseClicked

        //logica para validar que haya o no mesas
        if (obtenerTodas() == null) {
            insertMasivoMesas();
        } else {
            JOptionPane.showMessageDialog(this, "Error ya existen las mesas : ",
                    "Error en Registro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnInsertarMesasMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        app.mostrarPantallaRegistrarCliente();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        app.mostrarPantallaRegistrarIngrediente();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        app.mostrarPantallaRegistrarIngrediente();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        app.mostrarPantallaRegistrarIngrediente();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnBuscarCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliente1MouseClicked
        app.mostrarPantallaComandasActivas();
    }//GEN-LAST:event_btnBuscarCliente1MouseClicked

    private void btnBuscarCliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliente2MouseClicked
        app.mostrarMenuSelector();
    }//GEN-LAST:event_btnBuscarCliente2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        app.mostrarMenuReportes();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        app.mostrarMenuReportes();
    }//GEN-LAST:event_jLabel15MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarCliente1;
    private javax.swing.JLabel btnBuscarCliente2;
    private javax.swing.JLabel btnInsertarMesas;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel icnTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.PanelRound panelRound1;
    private GUI.PanelRound pnlBtnGuardarCliente2;
    private GUI.PanelRound pnlBtnGuardarCliente3;
    private GUI.PanelRound pnlBtnInsertarMesas;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeader1;
    private javax.swing.JTable tablaMesas;
    // End of variables declaration//GEN-END:variables
//Metodos que acceden a la base de datos.
    public void insertMasivoMesas() {
        try {
            // logica para insertas mesas , pero debe buscar primero para saber si hay o no hay
            app.insertMasivoMesas();
            JOptionPane.showMessageDialog(this, "¡Mesas ingresadas correctemente!\n " + "Total mesas : 20",
                    "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            validarMesasExistentes();
            pnlBtnInsertarMesas.setVisible(false);
            btnInsertarMesas.setVisible(false);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar las mesas : " + ex.getMessage(),
                    "Error en Registro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public List<MesaDTO> obtenerTodas() {
        try {
            List<MesaDTO> mesasCargadas = app.obtenerTodas();
            if (mesasCargadas == null || mesasCargadas.isEmpty()) {
                return null; // Si la lista es vacía, se retorna null
            }
            cargarMesasTabla(mesasCargadas);
            app.reconstruirPantallaMesero();
            return mesasCargadas;
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al consultar las mesas : " + ex.getMessage(),
                    "Error en Consulta", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
//Metodos Auxiliares

    public void centrarTextoTabla(JTable tabla) {
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);

        // Aplicar el renderizador a todas las columnas de la tabla
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(centrado);
        }
    }

    public void calcularHora() {
        Timer timer = new Timer(1000, e -> {
            LocalTime horaActual = LocalTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm a");
            hora.setText(horaActual.format(formatter));
        });
        timer.start();
    }

    public void validarMesasExistentes() {
        //logica para validar que haya o no mesas
        if (obtenerTodas() != null) {
            pnlBtnInsertarMesas.setVisible(false);
            btnInsertarMesas.setVisible(false);
        }
    }

    public void cargarMesasTabla(List<MesaDTO> mesasDTO) {

        DefaultTableModel model = (DefaultTableModel) tablaMesas.getModel();
        model.setRowCount(0);

        for (MesaDTO mesa : mesasDTO) {
            model.addRow(new Object[]{mesa.getNumeroMesa()});
        }

    }

}
