/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTOSalida.MesaDTO;
import exception.NegocioException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian Moreno
 */
public class MenuMesero extends javax.swing.JPanel {

    /**
     * Creates new form MenuMesero
     */
    Aplicacion app;

    public MenuMesero(Aplicacion app) {
        this.app = app;
        initComponents();
        mostrarFecha();
        validarMesasExistentes();
        centrarTextoTabla(tablaMesas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlBtnGuardarCliente1 = new GUI.PanelRound();
        btnBuscarCliente = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelRound1 = new GUI.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMesas = new javax.swing.JTable();
        pnlBtnGuardarCliente2 = new GUI.PanelRound();
        btnBuscarCliente1 = new javax.swing.JLabel();
        icnTiempo = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 202, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1150, 4));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Playfair Display", 1, 100)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Restaurante");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 15, -1, -1));

        pnlBtnGuardarCliente1.setBackground(new java.awt.Color(153, 0, 0));
        pnlBtnGuardarCliente1.setRoundBottomLeft(30);
        pnlBtnGuardarCliente1.setRoundBottomRight(30);
        pnlBtnGuardarCliente1.setRoundTopLeft(30);
        pnlBtnGuardarCliente1.setRoundTopRight(30);
        pnlBtnGuardarCliente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCliente.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente.setText("SALIR");
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarClienteMouseClicked(evt);
            }
        });
        pnlBtnGuardarCliente1.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 60));

        pnlHeader.add(pnlBtnGuardarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 62, 182, 60));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 180));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        jLabel16.setText("Rol : Empleado");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 40));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Playfair Display", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("INICIAR COMANDA EN MESA :");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        tablaMesas.setBackground(new java.awt.Color(255, 255, 255));
        tablaMesas.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 36)); // NOI18N
        tablaMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMesas.setRowHeight(80);
        jScrollPane1.setViewportView(tablaMesas);

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 590, 330));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 590, 380));

        pnlBtnGuardarCliente2.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnGuardarCliente2.setRoundBottomLeft(30);
        pnlBtnGuardarCliente2.setRoundBottomRight(30);
        pnlBtnGuardarCliente2.setRoundTopLeft(30);
        pnlBtnGuardarCliente2.setRoundTopRight(30);
        pnlBtnGuardarCliente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCliente1.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 18)); // NOI18N
        btnBuscarCliente1.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente1.setText("CONSULTAR COMANDAS ACTIVAS");
        btnBuscarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCliente1MouseClicked(evt);
            }
        });
        pnlBtnGuardarCliente2.add(btnBuscarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 340, 40));

        add(pnlBtnGuardarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 360, 40));

        icnTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiempo.png"))); // NOI18N
        add(icnTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, -1, -1));

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblHora.setText("10:00 PM");
        add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mesero2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 320, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarClienteMouseClicked
        app.mostrarMenuSelector();
    }//GEN-LAST:event_btnBuscarClienteMouseClicked

    private void btnBuscarCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCliente1MouseClicked
        app.mostrarPantallaComandasActivas();
    }//GEN-LAST:event_btnBuscarCliente1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarCliente;
    private javax.swing.JLabel btnBuscarCliente1;
    private javax.swing.JLabel icnTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHora;
    private GUI.PanelRound panelRound1;
    private GUI.PanelRound pnlBtnGuardarCliente1;
    private GUI.PanelRound pnlBtnGuardarCliente2;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tablaMesas;
    // End of variables declaration//GEN-END:variables
    //Metodos que acceden a la base de datos.
    public List<MesaDTO> obtenerTodas() {
        try {
            List<MesaDTO> mesasCargadas = app.obtenerTodas();
            if (mesasCargadas == null || mesasCargadas.isEmpty()) {
                return null; // Si la lista es vacía, se retorna null
            }
            cargarMesasTabla(mesasCargadas);
            return mesasCargadas;
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al consultar las mesas : " + ex.getMessage(),
                    "Error en Consulta", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }

    //metodos auxiliares
    private void mostrarFecha() {
        Timer timer = new Timer(1000, e -> {
            LocalTime horaActual = LocalTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm a");
            lblHora.setText(horaActual.format(formatter));
        });
        timer.start();
    }

    public void validarMesasExistentes() {
        //logica para validar que haya o no mesas
        if (obtenerTodas() != null) {

        }
    }

    public void centrarTextoTabla(JTable tabla) {
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);

        // Aplicar el renderizador a todas las columnas de la tabla
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(centrado);
        }
    }

    public void cargarMesasTabla(List<MesaDTO> mesasDTO) {

        DefaultTableModel model = (DefaultTableModel) tablaMesas.getModel();
        model.setRowCount(0);

        for (MesaDTO mesa : mesasDTO) {
            model.addRow(new Object[]{mesa.getNumeroMesa()});
        }

    }
}
