/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Sebastian Moreno
 */
public class MenuSelector extends javax.swing.JPanel {

    /**
     * Creates new form MenuSelector
     */
    private Aplicacion app;

    public MenuSelector(Aplicacion app) {
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlBotonEmpleado = new GUI.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlBotonAdministrador = new GUI.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 202, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1150, 4));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Playfair Display", 0, 120)); // NOI18N
        jLabel1.setText("Menu Selector");
        pnlHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 180));

        pnlBotonEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotonEmpleado.setRoundBottomLeft(30);
        pnlBotonEmpleado.setRoundBottomRight(30);
        pnlBotonEmpleado.setRoundTopLeft(30);
        pnlBotonEmpleado.setRoundTopRight(30);
        pnlBotonEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mesero.png"))); // NOI18N
        pnlBotonEmpleado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 36)); // NOI18N
        jLabel6.setText("EMPLEADO");
        pnlBotonEmpleado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 60));

        add(pnlBotonEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 330, 310));

        pnlBotonAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotonAdministrador.setRoundBottomLeft(30);
        pnlBotonAdministrador.setRoundBottomRight(30);
        pnlBotonAdministrador.setRoundTopLeft(30);
        pnlBotonAdministrador.setRoundTopRight(30);
        pnlBotonAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBotonAdministradorMouseClicked(evt);
            }
        });
        pnlBotonAdministrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ADMINISITRADOR.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBotonAdministrador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 180));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMINISTRADOR");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        pnlBotonAdministrador.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 310));

        add(pnlBotonAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 330, 310));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Playfair Display", 0, 80)); // NOI18N
        jLabel5.setText("Soy...");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 200, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBotonAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonAdministradorMouseClicked
        app.setRol("Administrador");
        app.mostrarMenuPrincipal();
    }//GEN-LAST:event_pnlBotonAdministradorMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        app.setRol("Administrador");
        app.mostrarMenuPrincipal();
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private GUI.PanelRound pnlBotonAdministrador;
    private GUI.PanelRound pnlBotonEmpleado;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
