/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ModuloClientesFrecuentes;

import GUI.Aplicacion;
import java.awt.Color;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

/**
 *
 * @author Sebastian Moreno
 */
public class PantallaRegistrarCliente extends javax.swing.JPanel {

    /**
     * Creates new form PantallaRegistrarCliente
     */
    Aplicacion app;

    public PantallaRegistrarCliente(Aplicacion app) {
        this.app = app;
        initComponents();
        mostrarFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlApellidoMaterno = new GUI.PanelRound();
        inputApellidoMaterno = new javax.swing.JTextField();
        pnlCorreo = new GUI.PanelRound();
        inputCorreo = new javax.swing.JTextField();
        pnlApellidoPaterno = new GUI.PanelRound();
        inputApellidoPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pnlBtnGuardarCliente = new GUI.PanelRound();
        btnCancelar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlTelefono = new GUI.PanelRound();
        inputTelefono = new javax.swing.JTextField();
        pnlNombre = new GUI.PanelRound();
        inputNombre = new javax.swing.JTextField();
        pnlBtnGuardarCliente1 = new GUI.PanelRound();
        btnBuscarCliente = new javax.swing.JLabel();
        pnlBtnGuardarCliente2 = new GUI.PanelRound();
        btnGuardarCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        icnTiempo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 202, 179));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 120)); // NOI18N
        jLabel1.setText("Registrar Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 180));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1150, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setText("APELLIDO MATERNO (OPCIONAL):");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setText("CORREO (OPCIONAL):");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText("APELLIDO PATERNO*:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        pnlApellidoMaterno.setBackground(new java.awt.Color(255, 255, 255));
        pnlApellidoMaterno.setRoundBottomLeft(30);
        pnlApellidoMaterno.setRoundBottomRight(30);
        pnlApellidoMaterno.setRoundTopLeft(30);
        pnlApellidoMaterno.setRoundTopRight(30);
        pnlApellidoMaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputApellidoMaterno.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        inputApellidoMaterno.setForeground(new java.awt.Color(204, 204, 204));
        inputApellidoMaterno.setText("Ingresar nombre de usuario");
        inputApellidoMaterno.setBorder(null);
        inputApellidoMaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputApellidoMaternoMouseClicked(evt);
            }
        });
        inputApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputApellidoMaternoActionPerformed(evt);
            }
        });
        pnlApellidoMaterno.add(inputApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 30));

        add(pnlApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 460, 50));

        pnlCorreo.setBackground(new java.awt.Color(255, 255, 255));
        pnlCorreo.setRoundBottomLeft(30);
        pnlCorreo.setRoundBottomRight(30);
        pnlCorreo.setRoundTopLeft(30);
        pnlCorreo.setRoundTopRight(30);
        pnlCorreo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputCorreo.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        inputCorreo.setForeground(new java.awt.Color(204, 204, 204));
        inputCorreo.setText("Ingresar nombre de usuario");
        inputCorreo.setBorder(null);
        inputCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputCorreoMouseClicked(evt);
            }
        });
        inputCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCorreoActionPerformed(evt);
            }
        });
        pnlCorreo.add(inputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 30));

        add(pnlCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 440, 50));

        pnlApellidoPaterno.setBackground(new java.awt.Color(255, 255, 255));
        pnlApellidoPaterno.setRoundBottomLeft(30);
        pnlApellidoPaterno.setRoundBottomRight(30);
        pnlApellidoPaterno.setRoundTopLeft(30);
        pnlApellidoPaterno.setRoundTopRight(30);
        pnlApellidoPaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputApellidoPaterno.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        inputApellidoPaterno.setForeground(new java.awt.Color(204, 204, 204));
        inputApellidoPaterno.setText("Ingresar nombre de usuario");
        inputApellidoPaterno.setBorder(null);
        inputApellidoPaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputApellidoPaternoMouseClicked(evt);
            }
        });
        inputApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputApellidoPaternoActionPerformed(evt);
            }
        });
        pnlApellidoPaterno.add(inputApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 30));

        add(pnlApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 460, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel5.setText("NOMBRE(S)*:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        pnlBtnGuardarCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnGuardarCliente.setRoundBottomLeft(30);
        pnlBtnGuardarCliente.setRoundBottomRight(30);
        pnlBtnGuardarCliente.setRoundTopLeft(30);
        pnlBtnGuardarCliente.setRoundTopRight(30);
        pnlBtnGuardarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("CANCELAR");
        pnlBtnGuardarCliente.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        add(pnlBtnGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 180, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setText("TELEFONO*:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        pnlTelefono.setBackground(new java.awt.Color(255, 255, 255));
        pnlTelefono.setRoundBottomLeft(30);
        pnlTelefono.setRoundBottomRight(30);
        pnlTelefono.setRoundTopLeft(30);
        pnlTelefono.setRoundTopRight(30);
        pnlTelefono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputTelefono.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        inputTelefono.setForeground(new java.awt.Color(204, 204, 204));
        inputTelefono.setText("Ingresar nombre de usuario");
        inputTelefono.setBorder(null);
        inputTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputTelefonoMouseClicked(evt);
            }
        });
        inputTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefonoActionPerformed(evt);
            }
        });
        pnlTelefono.add(inputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 30));

        add(pnlTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 350, 50));

        pnlNombre.setBackground(new java.awt.Color(255, 255, 255));
        pnlNombre.setRoundBottomLeft(30);
        pnlNombre.setRoundBottomRight(30);
        pnlNombre.setRoundTopLeft(30);
        pnlNombre.setRoundTopRight(30);
        pnlNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputNombre.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        inputNombre.setForeground(new java.awt.Color(204, 204, 204));
        inputNombre.setText("Ingresar nombre de usuario");
        inputNombre.setBorder(null);
        inputNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputNombreMouseClicked(evt);
            }
        });
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        pnlNombre.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 30));

        add(pnlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 450, 50));

        pnlBtnGuardarCliente1.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnGuardarCliente1.setRoundBottomLeft(30);
        pnlBtnGuardarCliente1.setRoundBottomRight(30);
        pnlBtnGuardarCliente1.setRoundTopLeft(30);
        pnlBtnGuardarCliente1.setRoundTopRight(30);
        pnlBtnGuardarCliente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCliente.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarCliente.setText("BUSCAR UN CLIENTE");
        pnlBtnGuardarCliente1.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 30));

        add(pnlBtnGuardarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 320, 50));

        pnlBtnGuardarCliente2.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnGuardarCliente2.setRoundBottomLeft(30);
        pnlBtnGuardarCliente2.setRoundBottomRight(30);
        pnlBtnGuardarCliente2.setRoundTopLeft(30);
        pnlBtnGuardarCliente2.setRoundTopRight(30);
        pnlBtnGuardarCliente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarCliente.setFont(new java.awt.Font("Product Sans Infanity", 0, 28)); // NOI18N
        btnGuardarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarCliente.setText("      GUARDAR CLIENTE");
        btnGuardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarClienteMouseClicked(evt);
            }
        });
        pnlBtnGuardarCliente2.add(btnGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario.png"))); // NOI18N
        pnlBtnGuardarCliente2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        add(pnlBtnGuardarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 320, 50));

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblHora.setText("10:00 PM");
        add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiencia.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, -1, -1));

        icnTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiempo.png"))); // NOI18N
        add(icnTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void inputApellidoMaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputApellidoMaternoMouseClicked
        if (inputApellidoMaterno.getText().equalsIgnoreCase("Ingresar nombre de usuario")) {
            inputApellidoMaterno.setText("");
            inputApellidoMaterno.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputApellidoMaternoMouseClicked

    private void inputApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApellidoMaternoActionPerformed

    private void inputCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCorreoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCorreoMouseClicked

    private void inputCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCorreoActionPerformed

    private void inputApellidoPaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputApellidoPaternoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApellidoPaternoMouseClicked

    private void inputApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApellidoPaternoActionPerformed

    private void inputTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputTelefonoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefonoMouseClicked

    private void inputTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefonoActionPerformed

    private void inputNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreMouseClicked

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void btnGuardarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarClienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarCliente;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnGuardarCliente;
    private javax.swing.JLabel icnTiempo;
    private javax.swing.JTextField inputApellidoMaterno;
    private javax.swing.JTextField inputApellidoPaterno;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHora;
    private GUI.PanelRound pnlApellidoMaterno;
    private GUI.PanelRound pnlApellidoPaterno;
    private GUI.PanelRound pnlBtnGuardarCliente;
    private GUI.PanelRound pnlBtnGuardarCliente1;
    private GUI.PanelRound pnlBtnGuardarCliente2;
    private GUI.PanelRound pnlCorreo;
    private GUI.PanelRound pnlNombre;
    private GUI.PanelRound pnlTelefono;
    // End of variables declaration//GEN-END:variables
public void mostrarFecha() {
        Timer timer = new Timer(1000, e -> {
            LocalTime horaActual = LocalTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm a");
            lblHora.setText(horaActual.format(formatter));
        });
        timer.start();
    }
}
